version: '3.1'

services:
    mongodb:
        image: mongo
        networks:
            - production-network
        environment:
            MONGO_INITDB_DATABASE : star_wars_db
        volumes:
            - "../scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
    golang:
        build:
            dockerfile: ./build/package/Dockerfile
            context: ../
        image: wallacebenevides/star-wars-api
        container_name: star-wars-api
        ports:
            - "8080:8080"
        networks:
            - production-network
        depends_on:
            - mongodb
networks:
    production-network:
        driver: bridge
